behaviors:
    ArcadeDriver:
        trainer_type: ppo
        hyperparameters:
            batch_size: 1024
            beta: 7.0e-3
            buffer_size: 10240
            epsilon: 0.2
            lambd: 0.95
            learning_rate: 3.0e-4
            learning_rate_schedule: linear
            num_epoch: 3
        network_settings:
            vis_encode_type: simple
            normalize: false
            hidden_units: 128
            num_layers: 2
            memory_size: 256
            time_horizon: 64
            sequence_length: 64
            use_recurrent: false
        max_steps: 10000000
        summary_freq: 10000
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
        threaded: true
